### ISSUE TITLE
utils.cython_bbox

### ISSUE THREAD

**Issue by hensonwells** [Zhongdao/Towards-Realtime-MOT#40]
when i run the demo.py,i got this:
`from utils.cython_bbox import bbox_ious
ModuleNotFoundError: No module named 'utils.cython_bbox'`
Is anything I have to download or compile?
Wish u help

**Comment by ThanhPham1987** [comment]
Me too

**Comment by hensonwells** [comment]
> Me too
I turn to python 3.6,it seems work,maybe u can try it.

**Comment by ThanhPham1987** [comment]
I use python 3.6 . Like you. Can you communication via skype: quangthanh1987 to discus together ?

**Comment by yanfengliu** [comment]
Following suggestions from https://github.com/Zhongdao/Towards-Realtime-MOT/issues/13
do `pip install cython_bbox`,
then change in `matching.py` from `utils.cython_bbox import bbox_ious` to `from cython_bbox import bbox_overlaps as bbox_ious`

---
If you have trouble with the official pip package of `cython_bbox`, it's probably because you are running windows. In that case, clone my repo https://github.com/yanfengliu/cython_bbox and run `pip install .` from its directory.

**Comment by chandanrao007** [comment]
Thanks a ton @yanfengliu
