### ISSUE TITLE
Some questions to the network architecture

### ISSUE THREAD

**Issue by Srenpan** [Zhongdao/Towards-Realtime-MOT#49]
Hi,  this is a wonderful work on MOT.
I have some questions to the architecture.
Paper indicate that network choose FPN as base architecture, and I study Feature Pyramid Network (FPN) (Lin et al. 2017) the backbone is ResNets. But the implement backbone seems to be YOLOv3. 
Is that network choose FPN as base architecture just the concept or use the specific network ?
I check YOLOv3 has three different scale feature maps, are these means the FPN?
I can't find the feature map with the different scale fused by skip connection,  can somebody point where the code is?
And another question is RPN anchor choose from yolo layer with different scales?
thanks

**Comment by Zhongdao** [comment]
Actually the network architecture of Yolov3 is very similar to FPN except for several differences:
1. Yolov3 fuses 3 different scales rather than 5 in FPN.
2. The backbone of yolov3 is darknet.
3. The classification/regression head is not shared across different scales in yolov3.

As you mentioned,  I think FPN is a concept rather than a specific network, and the network used in yolov3 is only a special case.

**Comment by Srenpan** [comment]
@Zhongdao, I got it, thank you for this kind reply.

**Comment by ZongweiZhou1** [comment]
@Zhongdao 
This is a wonderful work. 
Do you test the performance when the backbone is replaced by the FPN with ResNet50?

**Comment by Zhongdao** [comment]
@ZongweiZhou1 Yes, you can check Figure 4 in our paper.
